.TH IWGTK "1" "August 2020" "iwgtk" "iwgtk manpage"

.SH NAME
iwgtk \- Graphical wifi management utility

.SH SYNOPSIS
iwgtk [\fIOPTION\fR]

.SH DESCRIPTION
iwgtk is a graphical utility for managing wifi networks via iwd.
Supported functionality is similar to that of iwctl.

.TP
\fB\-i\fR, \fB\-\-indicators\fR
Enable indicator (tray) icons and run iwgtk in the background

.TP
\fB\-n\fR, \fB\-\-notifications\fR
Enable desktop notifications (default)

.TP
\fB\-N\fR, \fB\-\-no\-notifications\fR
Disable desktop notifications

.TP
\fB\-s\fR, \fB\-\-signal\-strength\-icons\fR
Display signal strength levels as icons (default)

.TP
\fB\-S\fR, \fB\-\-signal\-strength\-numeric\fR
Display signal strength levels numerically, in dBm

.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options

.TP
\fB\-V\fR, \fB\-\-version\fR
Print version

.SH "REPORTING BUGS"
Report bugs using the issue tracker on Github <https://github.com/J-Lentz/iwgtk/issues>.

.SH "COPYRIGHT"
Copyright 2020 Jesse Lentz

iwgtk is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

iwgtk is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with iwgtk.  If not, see <https://www.gnu.org/licenses/>.
